name: flutter_drawing_board
description: A Flutter package of drawing board, provides basic drawing tools, canvas operations, and image data acquisition.
version: 0.5.0
homepage: https://github.com/fluttercandies/flutter_drawing_board

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hsvcolor_picker: ^1.2.3
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec



# The following section is specific to Flutter.
flutter:
